name: Create Release on Tag Push

on:
  push:
    tags:
      - '*'  # Triggers on any tag push

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows creating a release

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Extract the tag name
      - name: Extract tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Step 3: Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: "Automated release for tag ${{ env.TAG_NAME }}"
          draft: false
          prerelease: false
